import { Inter } from "next/font/google";
import { OrderProvider } from "./context/OrderContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Thermal Contractor",
  description: "Generated by Vordx",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="__next" className={inter.className}>
        <OrderProvider>{children}</OrderProvider>
      </body>
    </html>
  );
}
