import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Thermal",
  description: "Generated by Vordx",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  id="__next" className={inter.className}>{children}</body>
    </html>
  );
}
